/* Data induk warga RT 10 / RW 021 - Blok, Nomor Rumah, Nama Kepala Keluarga.
   Sumber: Update Data Warga RT 10 RW 21 (Juni 2025). Total 90 rumah.
   Format tiap baris:
     { "blok": "D3A", "no": "12", "nama": "NAMA KEPALA KELUARGA" },
   Kalau ada rumah baru / ganti nama, edit di sini DAN di config.js > daftarRumah
   (format "D3A No.12"), lalu upload ulang kedua file ke GitHub. */
const WARGA_DATA = [
  { "blok": "D3A", "no": "1", "nama": "Bpk. AAN KRISTIANTO" },
  { "blok": "D3A", "no": "2", "nama": "Bpk. RANDY FAHRIDAL" },
  { "blok": "D3A", "no": "3", "nama": "Bpk. DENNY HERMAWAN" },
  { "blok": "D3A", "no": "3A", "nama": "Bpk. DWI KISWANTO" },
  { "blok": "D3A", "no": "8", "nama": "Bpk. SURATMAN" },
  { "blok": "D3A", "no": "9", "nama": "Bpk. TONERI" },
  { "blok": "D3A", "no": "10", "nama": "Bpk. ARI RIYADHI" },
  { "blok": "D3A", "no": "11", "nama": "Bpk. INDRA LESMANA" },
  { "blok": "D3B", "no": "3", "nama": "Bpk. FERANTO SUPU (Alm.)" },
  { "blok": "D3B", "no": "3A", "nama": "Bpk. TRI SUPRIYANTO" },
  { "blok": "D3B", "no": "5", "nama": "Bpk. WIYATNO" },
  { "blok": "D3B", "no": "6", "nama": "Bpk. RONI" },
  { "blok": "D4A", "no": "3", "nama": "Bpk. CARMA S." },
  { "blok": "D4A", "no": "3A", "nama": "Bpk. RAHMAN" },
  { "blok": "D4A", "no": "6", "nama": "Bpk. AMIR / UMI IDA" },
  { "blok": "D4A", "no": "7", "nama": "Bpk. SAMIRAN" },
  { "blok": "D4A", "no": "8", "nama": "Bpk. MUKHRONI" },
  { "blok": "D4A", "no": "9", "nama": "Bpk. HERI" },
  { "blok": "D4A", "no": "10", "nama": "Bpk. AHMAD RUSDI" },
  { "blok": "D4A", "no": "12", "nama": "Bpk. ISMANUEL KARO" },
  { "blok": "D4B", "no": "1", "nama": "Bpk. EWIN" },
  { "blok": "D4B", "no": "2", "nama": "Bpk. HADI PURWOKO" },
  { "blok": "D4B", "no": "3", "nama": "Bpk. ANDHIKA PRATAMA" },
  { "blok": "D4B", "no": "3A", "nama": "Bpk. M. SYARIFUDIN" },
  { "blok": "D4B", "no": "7", "nama": "Bpk. MAULANA" },
  { "blok": "D4B", "no": "9", "nama": "Bpk. FAJAR" },
  { "blok": "D5A", "no": "2", "nama": "Bpk. YUSUF" },
  { "blok": "D5A", "no": "3", "nama": "Bpk. MUJIYONO" },
  { "blok": "D5A", "no": "3A", "nama": "Bpk. YULIYANTO" },
  { "blok": "D5A", "no": "5", "nama": "Bpk. SURYADI" },
  { "blok": "D5A", "no": "6", "nama": "Bpk. ANDY YUNANTO" },
  { "blok": "D5A", "no": "7", "nama": "Bpk. SODIQIN" },
  { "blok": "D5A", "no": "9", "nama": "Bpk. ADITYAWARMAN" },
  { "blok": "D5A", "no": "10", "nama": "Bpk. NU’MAN H." },
  { "blok": "D5A", "no": "12", "nama": "Bpk. ALAMSYAH" },
  { "blok": "D5A", "no": "14", "nama": "Bpk. AHMAD SAYFULLOH" },
  { "blok": "D5A", "no": "16", "nama": "Bpk. CATUR" },
  { "blok": "D5A", "no": "18", "nama": "Bpk. SUJARWOKO" },
  { "blok": "D5A", "no": "20", "nama": "Bpk. AGUS WAHYUDI" },
  { "blok": "D5A", "no": "21", "nama": "Bpk. PARDI" },
  { "blok": "D5A", "no": "22", "nama": "Bpk. SUGENG" },
  { "blok": "D5A", "no": "23", "nama": "Bpk. SUPARMAN" },
  { "blok": "D5B", "no": "2", "nama": "Bpk. SAMARI" },
  { "blok": "D5B", "no": "3A", "nama": "Bpk. AMIR" },
  { "blok": "D5B", "no": "5", "nama": "Bpk. KHORIYANTO" },
  { "blok": "D5B", "no": "6", "nama": "Bpk. WAHYU" },
  { "blok": "D5B", "no": "8", "nama": "Bpk. GAYUH" },
  { "blok": "D5B", "no": "9", "nama": "Bpk. HAMID" },
  { "blok": "D5B", "no": "10", "nama": "Bpk. EDY P." },
  { "blok": "D5B", "no": "12", "nama": "Bpk. IMAM" },
  { "blok": "D5B", "no": "14", "nama": "Bpk. LULUS / MOKO" },
  { "blok": "D5B", "no": "15", "nama": "Bpk. BIRLIN DWI A." },
  { "blok": "D5B", "no": "16", "nama": "Bpk. SLAMET" },
  { "blok": "D5B", "no": "17", "nama": "Bpk. ALI" },
  { "blok": "D5B", "no": "18", "nama": "Bpk. EKO WIDIANTO" },
  { "blok": "D5B", "no": "19", "nama": "Bpk. SIGIT FIRMANSYAH" },
  { "blok": "D5B", "no": "20", "nama": "Bpk. IRAWAN" },
  { "blok": "D5B", "no": "21", "nama": "Bpk. NOVIAN" },
  { "blok": "D5B", "no": "22", "nama": "Bpk. FIKRI" },
  { "blok": "D5B", "no": "23", "nama": "Bpk. DHAFIR" },
  { "blok": "D5C", "no": "1", "nama": "Bpk. ANDERSON" },
  { "blok": "D5C", "no": "2", "nama": "Bpk. HENDI FUAD A." },
  { "blok": "D5C", "no": "3", "nama": "Bpk. AHMAD" },
  { "blok": "D5C", "no": "3A", "nama": "Bpk. NURZAKI" },
  { "blok": "D5C", "no": "5", "nama": "Bpk. ADE BARNAS" },
  { "blok": "D5C", "no": "6", "nama": "Bpk. AGUS SALIM" },
  { "blok": "D5C", "no": "7", "nama": "Bpk. MUGI" },
  { "blok": "D5C", "no": "8", "nama": "Bpk. YOHAN SOFYAN" },
  { "blok": "D5C", "no": "9", "nama": "Bpk. FRENGKI" },
  { "blok": "D5C", "no": "11", "nama": "Bpk. PUGUH" },
  { "blok": "D5C", "no": "12", "nama": "Bpk. SEPTIAN" },
  { "blok": "D5C", "no": "14", "nama": "Bpk. SABAR" },
  { "blok": "D5C", "no": "15", "nama": "Bpk. HARI S." },
  { "blok": "D5C", "no": "16", "nama": "Bpk. SYARIF" },
  { "blok": "D5C", "no": "17", "nama": "Ibu BUDI" },
  { "blok": "D5C", "no": "18", "nama": "Bpk. DEDI LUKMANTO" },
  { "blok": "D5C", "no": "19", "nama": "Bpk. ROMDHON" },
  { "blok": "D5C", "no": "20", "nama": "Bpk. AHMAD MUIS" },
  { "blok": "D5C", "no": "21", "nama": "Bpk. SANDI" },
  { "blok": "D5C", "no": "22", "nama": "Bpk. CANDRA" },
  { "blok": "D5C", "no": "23", "nama": "Bpk. PARDIANA" },
  { "blok": "D6", "no": "3", "nama": "Bpk. AWAN" },
  { "blok": "D6", "no": "3A", "nama": "Bpk. EKA SAPTO EDI" },
  { "blok": "D6", "no": "5", "nama": "Bpk. MUHAMMAD ISA" },
  { "blok": "D6", "no": "7", "nama": "Bpk. HADI SETYONO" },
  { "blok": "D6", "no": "9", "nama": "Bpk. ANDRI SETIAWAN" },
  { "blok": "D6", "no": "12", "nama": "Bpk. EKO ANGGIT" },
  { "blok": "D6", "no": "12A", "nama": "Bpk. KHAFIF JUNIARTO" },
  { "blok": "D6", "no": "14", "nama": "Bpk. ALI" },
  { "blok": "D6", "no": "15", "nama": "Bpk. FERRY ALFANDI" },
];
